version: '3.8'

volumes:
    SmartSchoolDB:

networks:
    mysqlNET:
    smartschoolNET:

services:

    mysql:
          image: "mysql:5.7"
          container_name: mysql
          ports:
            - "3306:3306"
          volumes:
            - "SmartSchoolDB:/var/lib/mysql"
          networks:
            - mysqlNET

          environment:
            - MYSQL_ROOT_PASSWORD=senha 
            - bind-address:0.0.0.0 
            - MYSQL_PASSWORD=senha 
            - MYSQL_ROOT_HOST=%

    smartschool:
          build:
              context: .
              dockerfile: Dockerfile
          container_name: smartschool

          networks:
            - mysqlNET
            - smartschoolNET
          ports:
            - 5000:80
          environment:
            - DBHOST=mysql
          depends_on:
            - mysql

